image: jangrewe/gitlab-ci-android

stages:
- build
- deploy

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
 
build:
  stage: build
  script:
  - chmod 755 gradlew
  - "echo build_stage: $CI_BUILD_ID >> build"
  - ./gradlew clean
  - ./gradlew build
  - 'ls -al build'
  cache:
    paths:
    - build
  artifacts:
    name: "build-artifacts-${CI_BUILD_REF}"
    paths:
    - build
    name: "$CI_BUILD_ID $(date +%F)"
    expire_in: 1 month 


only-build:
  stage: deploy
  dependencies:
  - build
  script:
  - ls -al *   
  - 'ls -al build'
  