image: jangrewe/gitlab-ci-android
stages:
- build
- finish
before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_BUILD_ID}
  paths:
  - .gradle/
  - .gradle/wrapper
  - .gradle/caches
  - build/
  - app/build

build :
    stage: build    
    script:
    - chmod 755 gradlew
    - "echo build: $CI_BUILD_ID >> build"
    - ./gradlew build
    cache:
        paths:
        - .gradle/
        - .gradle/wrapper
        - .gradle/caches
        - build/
        - app/build
    artifacts:
        paths:
        - build/*

finish:
  stage: finish
  dependencies: 
    - build
  script:
    - ls -al

