image: jangrewe/gitlab-ci-android

stages:
- quality
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

quality :
    stage: quality                                                   # 1. stage Quality
    environment: DEV
    script:
    -  chmod 755 gradlew
    - ./gradlew  assemble${Environment}Debug                          # generate the build (Environment - PROD,STG,DEV)
    - ./gradlew  --stacktrace assemble countDEVDebugDexMethods
    - ./gradlew  lintDEVDebug                              # command to execute the lint
    - ./gradlew  --stacktrace assemble customfindbugs               # command to execute the findbug
    - ./gradlew  --stacktrace assemble pmd
    - ./gradlew  --stacktrace assemble checkstyle                   # command to execute the checkstyle
    artifacts:
      paths:
          - app/build/outputs/dexcount/DEVDebug.txt           # path dexcount result
          - app/build/outputs/findbugs/findbugs.html                     # path findbugs result
          - app/build/outputs/checkstyle/checkstyle.html                 # path checkstyle result
          - app/build/outputs/pmd/pmd.html                               # path pmd result

      name: "$CI_BUILD_NAME $(date +%F)"                             # Download file name eg - 'quality_2017-01-13.zip'
      expire_in: 1 month                                             # Uploaded artifacts get deleted after 1 month

build :
    stage: build
    script:
    - chmod 755 gradlew
    - ./gradlew clean
    - ./gradlew assembledebug
    artifacts:
        paths:
        - app/build/outputs/apk/app-debug.apk