image: jangrewe/gitlab-ci-android

stages:
- build
- test
- deploy

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
 
build:
  stage: build
  script:
  - chmod 755 gradlew
  - "echo build_stage: $CI_BUILD_ID >> build"
  - ./gradlew clean
  - ./gradlew build
  cache:
    paths:
    - build
  artifacts:
    name: "build-artifacts-${CI_BUILD_REF}"
    paths:
    - build
    name: "$CI_BUILD_ID $(date +%F)"
    expire_in: 1 month            
    
test1:
  stage: test
  script:
  - "echo test_stage: $CI_BUILD_ID >> test1"
  - ls -al
  artifacts:
    paths:
    - test1

test2:
  stage: test
  script:
  - "echo test_stage: $CI_BUILD_ID >> test2"
  - ls -al
  artifacts:
    paths:
    - test2

only-build:
  stage: deploy
  dependencies:
  - build
  script:
  - chmod 755 gradlew
  - "echo deploy : $CI_BUILD_ID >> deploy"
  ###- ./gradlew clean
  ###- ./gradlew build
  - ls -al test1
  - ls -al test2
  - ls -al build
  