image: jangrewe/gitlab-ci-android

stages:
- build                                                    # 2. javadoc documentation
- test
- test1

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
 

build :
    stage: build        
    script:
    - chmod 755 gradlew
    - "echo build: $CI_BUILD_ID >> build"
    - ./gradlew clean
    - ./gradlew build
    artifacts:
        paths:
        - build/*
        - app/build/outputs/apk/app-debug.apk
        name: "$CI_BUILD_ID $(date +%F)"         # Download file name eg - 'documentation_2017-01-13.zip'
        expire_in: 1 month                         # Uploaded artifacts get deleted after 1 month

test :
    stage: test    
    dependencies:
    - build
    script:
    - chmod 755 gradlew
    - "echo test: $CI_BUILD_ID >> test"
    #- ./gradlew clean
    - ls -al build/
    - ./gradlew build
    artifacts:
        paths:
        - test/*     
        name: "$CI_BUILD_ID $(date +%F)"         # Download file name eg - 'documentation_2017-01-13.zip'
        expire_in: 1 month                         # Uploaded artifacts get deleted after 1 month
        
test2 :
    stage: test2    
    dependencies:
    - test
    script:
    - chmod 755 gradlew
    - "echo test: $CI_BUILD_ID >> test"
    #- ./gradlew clean
    - ls -al test/
    - ./gradlew build
    artifacts:
        paths:
        - test1/*     
        name: "$CI_BUILD_ID $(date +%F)"         # Download file name eg - 'documentation_2017-01-13.zip'
        expire_in: 1 month                         # Uploaded artifacts get deleted after 1 month
        
